apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-node-app-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  MESSAGE: "Hello again, I am testing the hook"
  VERSION: "v1.1.0"
