apiVersion: batch/v1
kind: Job
metadata:
  name: presync-message-job
  annotations:
    argocd.argocj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: print-message
        image: busybox:1.36
        command: ["sh", "-c", "echo '===== PreSync Hook is running! ====='"]
      restartPolicy: Never
  backoffLimit: 0