apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.0.2
    
    helm:
      values: |
        architecture: standalone
        
        auth:
          enabled: true
          password: "myredispassword123"
        
        master:
          count: 1
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              memory: 128Mi
              cpu: 100m
          persistence:
            enabled: false
        
        service:
          type: ClusterIP
          port: 6379
        
        metrics:
          enabled: true
          resources:
            limits:
              memory: 64Mi
              cpu: 50m
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true